# 2. Data Acquisition and Understanding

## 2.1 Data Acquisition and Dataset Structure

In [1]:
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv("../data/patient_data.csv")

# Keep an unchanged copy of the original dataset
df_original = df.copy(deep=True)

df.head()

,composite_key,age_level,gender,bmi_level,smoking,diabetes,age,age_normalized,bmi,hypertension,...,salt_intake,heart_rate,hdl,ldl,education_level,employment_status,source_dataset,disease_flags,sublabel,label
0,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,9,0.080460,19.20,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
1,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.55,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
2,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,22.89,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
3,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,3,0.011494,23.12,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal
4,Young_Female_Normal_Never_No,Young,Female,Normal,Never,No,4,0.022989,19.61,0.0,...,8.685304,74.329073,65.651757,129.220447,Primary,Retired,diabetes,"0,0,0",N,Normal

In [3]:
print("Number of records:", df_original.shape[0])
print("Number of columns:", df_original.shape[1])

Number of records: 280985
Number of columns: 39

In [4]:
df_original.info()

<class 'pandas.DataFrame'>
RangeIndex: 280985 entries, 0 to 280984
Data columns (total 39 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   composite_key         280985 non-null  str
 1   age_level             280985 non-null  str
 2   gender                280985 non-null  str
 3   bmi_level             280985 non-null  str
 4   smoking               280985 non-null  str
 5   diabetes              280985 non-null  str
 6   age                   280985 non-null  int64
 7   age_normalized        280985 non-null  float64
 8   bmi                   280985 non-null  float64
 9   hypertension          280985 non-null  float64
 10  heart_disease         280985 non-null  float64
 11  HbA1c_level           280985 non-null  float64
 12  glucose               280985 non-null  float64
 13  cholesterol           280985 non-null  float64
 14  sleep_hours           280985 non-null  float64
 15  triglycerides         280985 non-null  float64
 16  physical_activity     280985 non-null  str
 17  family_history        280985 non-null  str
 18  stress_level          280985 non-null  str
 19  low_hdl_cholesterol   280985 non-null  str
 20  high_ldl_cholesterol  280985 non-null  str
 21  blood_pressure        280985 non-null  float64
 22  high_blood_pressure   280985 non-null  str
 23  sugar_consumption     280985 non-null  str
 24  crp_level             280985 non-null  float64
 25  homocysteine_level    280985 non-null  float64
 26  systolic_bp           280985 non-null  float64
 27  diastolic_bp          280985 non-null  float64
 28  alcohol_intake        280985 non-null  float64
 29  salt_intake           280985 non-null  float64
 30  heart_rate            280985 non-null  float64
 31  hdl                   280985 non-null  float64
 32  ldl                   280985 non-null  float64
 33  education_level       280985 non-null  str
 34  employment_status     280985 non-null  str
 35  source_dataset        280985 non-null  str
 36  disease_flags         280985 non-null  str
 37  sublabel              280985 non-null  str
 38  label                 280985 non-null  str
dtypes: float64(19), int64(1), str(19)
memory usage: 83.6 MB

In [5]:
df_original.dtypes

composite_key               str
age_level                   str
gender                      str
bmi_level                   str
smoking                     str
diabetes                    str
age                       int64
age_normalized          float64
bmi                     float64
hypertension            float64
heart_disease           float64
HbA1c_level             float64
glucose                 float64
cholesterol             float64
sleep_hours             float64
triglycerides           float64
physical_activity           str
family_history              str
stress_level                str
low_hdl_cholesterol         str
high_ldl_cholesterol        str
blood_pressure          float64
high_blood_pressure         str
sugar_consumption           str
crp_level               float64
homocysteine_level      float64
systolic_bp             float64
diastolic_bp            float64
alcohol_intake          float64
salt_intake             float64
heart_rate              float64
hdl                     float64
ldl                     float64
education_level             str
employment_status           str
source_dataset              str
disease_flags               str
sublabel                    str
label                       str
dtype: object

In [6]:
df_original.columns.tolist()

['composite_key',
 'age_level',
 'gender',
 'bmi_level',
 'smoking',
 'diabetes',
 'age',
 'age_normalized',
 'bmi',
 'hypertension',
 'heart_disease',
 'HbA1c_level',
 'glucose',
 'cholesterol',
 'sleep_hours',
 'triglycerides',
 'physical_activity',
 'family_history',
 'stress_level',
 'low_hdl_cholesterol',
 'high_ldl_cholesterol',
 'blood_pressure',
 'high_blood_pressure',
 'sugar_consumption',
 'crp_level',
 'homocysteine_level',
 'systolic_bp',
 'diastolic_bp',
 'alcohol_intake',
 'salt_intake',
 'heart_rate',
 'hdl',
 'ldl',
 'education_level',
 'employment_status',
 'source_dataset',
 'disease_flags',
 'sublabel',
 'label']

In [7]:
df_original.shape

(280985, 39)

## 2.2 Initial Data Quality Inspection

In [8]:
# Check for missing values in each column
missing_values = df_original.isnull().sum()
missing_values[missing_values > 0]

Series([], dtype: int64)

In [9]:
# Count fully duplicated rows
print("Duplicate rows:", df_original.duplicated().sum())

Duplicate rows: 2284

In [10]:
# Check the number of unique values in each column
for column in df_original.columns:
    print(f"{column}: {df_original[column].nunique()} unique values")

composite_key: 192 unique values
age_level: 4 unique values
gender: 2 unique values
bmi_level: 4 unique values
smoking: 3 unique values
diabetes: 2 unique values
age: 88 unique values
age_normalized: 151 unique values
bmi: 14122 unique values
hypertension: 137 unique values
heart_disease: 125 unique values
HbA1c_level: 192 unique values
glucose: 154 unique values
cholesterol: 323 unique values
sleep_hours: 10092 unique values
triglycerides: 525 unique values
physical_activity: 3 unique values
family_history: 2 unique values
stress_level: 3 unique values
low_hdl_cholesterol: 2 unique values
high_ldl_cholesterol: 2 unique values
blood_pressure: 197 unique values
high_blood_pressure: 2 unique values
sugar_consumption: 3 unique values
crp_level: 9992 unique values
homocysteine_level: 9996 unique values
systolic_bp: 275 unique values
diastolic_bp: 245 unique values
alcohol_intake: 486 unique values
salt_intake: 316 unique values
heart_rate: 235 unique values
hdl: 254 unique values
ldl: 304 unique values
education_level: 3 unique values
employment_status: 3 unique values
source_dataset: 3 unique values
disease_flags: 8 unique values
sublabel: 8 unique values
label: 2 unique values

In [11]:
# Inspect the distributions and ranges of numerical variables
df_original.describe().T

,count,mean,std,min,25%,50%,75%,max
age,280985.0,49.665865,21.682350,2.000000,32.000000,50.000000,67.000000,89.000000
age_normalized,280985.0,0.547883,0.249222,0.000000,0.344827,0.551724,0.747126,1.000000
bmi,280985.0,27.490663,7.040373,10.010000,22.100000,27.320000,32.700000,95.690000
hypertension,280985.0,0.128218,0.187346,0.000000,0.000000,0.071429,0.217063,1.000000
heart_disease,280985.0,0.073390,0.138243,0.000000,0.000000,0.007299,0.115053,1.000000
HbA1c_level,280985.0,5.947475,0.954072,3.500000,5.384805,5.800000,6.865766,9.000000
glucose,280985.0,135.258646,38.477865,70.000000,100.000000,138.000000,160.000000,300.000000
cholesterol,280985.0,224.045525,35.525530,150.000000,202.000000,225.000000,243.000000,300.000000
sleep_hours,280985.0,6.954652,1.426412,4.000000,6.200000,6.975185,7.700000,10.000000
triglycerides,280985.0,178.995744,67.336085,50.000000,129.000000,179.000000,242.000000,400.000000
blood_pressure,280985.0,149.887200,4.148644,120.000000,148.946429,149.713320,150.720942,180.000000
crp_level,280985.0,7.489127,1.013898,0.003647,7.294863,7.458483,7.758562,14.997087
homocysteine_level,280985.0,12.465326,0.983375,5.000236,12.287763,12.488407,12.686175,19.999037
systolic_bp,280985.0,134.405105,20.542140,90.000000,126.000000,134.167413,143.000000,179.000000
diastolic_bp,280985.0,89.476720,13.667219,60.000000,84.000000,89.504587,95.000000,119.000000
alcohol_intake,280985.0,15.003336,6.830255,0.000000,12.000000,14.982818,17.900000,30.000000
salt_intake,280985.0,8.480577,2.960646,2.000000,7.200000,8.477600,9.800000,15.000000
heart_rate,280985.0,74.497343,11.402996,50.000000,70.000000,74.487247,79.000000,99.000000
hdl,280985.0,64.609147,15.938525,30.000000,58.000000,64.650655,72.000000,99.000000
ldl,280985.0,129.725919,27.352521,70.000000,118.000000,129.983051,141.000000,189.000000

In [12]:
# Inspect the values and frequencies of all categorical columns
categorical_columns = df_original.select_dtypes(include="object").columns

for column in categorical_columns:
    print(f"\n{column}")
    print(df_original[column].value_counts(dropna=False))

C:\Users\leoca\AppData\Local\Temp\ipykernel_17176\3983996607.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df_original.select_dtypes(include="object").columns

composite_key
composite_key
Middle_Female_Overweight_Never_No      6097
Mature_Female_Overweight_Never_No      5778
Middle_Female_Obese_Never_No           5020
Mature_Female_Obese_Never_No           4986
Middle_Female_Normal_Never_No          4806
                                       ...
Young_Female_Underweight_Current_No     184
Young_Female_Underweight_Never_Yes      176
Young_Male_Underweight_Former_Yes       175
Young_Male_Underweight_Current_Yes      161
Young_Female_Underweight_Former_Yes     147
Name: count, Length: 192, dtype: int64

age_level
age_level
Mature    87632
Middle    85344
Senior    70225
Young     37784
Name: count, dtype: int64

gender
gender
Female    148763
Male      132222
Name: count, dtype: int64

bmi_level
bmi_level
Obese          98377
Overweight     79172
Normal         70596
Underweight    32840
Name: count, dtype: int64

smoking
smoking
Never      127764
Former      80380
Current     72841
Name: count, dtype: int64

diabetes
diabetes
No     180351
Yes    100634
Name: count, dtype: int64

physical_activity
physical_activity
High        120019
Moderate     80723
Low          80243
Name: count, dtype: int64

family_history
family_history
No     157182
Yes    123803
Name: count, dtype: int64

stress_level
stress_level
High      101298
Medium     90274
Low        89413
Name: count, dtype: int64

low_hdl_cholesterol
low_hdl_cholesterol
No     225935
Yes     55050
Name: count, dtype: int64

high_ldl_cholesterol
high_ldl_cholesterol
Yes    146442
No     134543
Name: count, dtype: int64

high_blood_pressure
high_blood_pressure
Yes    142168
No     138817
Name: count, dtype: int64

sugar_consumption
sugar_consumption
Low       123242
Medium     87362
High       70381
Name: count, dtype: int64

education_level
education_level
Tertiary     105285
Secondary     88914
Primary       86786
Name: count, dtype: int64

employment_status
employment_status
Unemployed    95884
Retired       95268
Employed      89833
Name: count, dtype: int64

source_dataset
source_dataset
hypertension    174982
diabetes         96128
heart             9875
Name: count, dtype: int64

disease_flags
disease_flags
0,0,0    106884
0,0,1     69806
1,0,1     66473
1,0,0     31918
0,1,0      2595
1,1,0      1398
0,1,1      1066
1,1,1       845
Name: count, dtype: int64

sublabel
sublabel
N           106884
HY           69806
DI_HY        66473
DI           31918
HT            2595
DI_HT         1398
HT_HY         1066
DI_HT_HY       845
Name: count, dtype: int64

label
label
Abnormal    174101
Normal      106884
Name: count, dtype: int64

In [13]:
# Investigate heart_disease because it was expected to be binary
print(df_original["heart_disease"].value_counts(dropna=False))
print("Unique values:", df_original["heart_disease"].unique())

heart_disease
0.000000    121656
1.000000      3923
0.222222      3845
0.032258      3074
0.080000      3040
             ...
0.000776       255
0.218220       240
0.000300       199
0.090909       185
0.166667       169
Name: count, Length: 125, dtype: int64
Unique values: [0.00000000e+00 1.00000000e+00 5.53359684e-02 1.67968750e-01
 5.68993953e-02 3.58422939e-03 2.33333333e-01 8.00915332e-03
 3.33333333e-01 4.28571429e-02 8.81971466e-02 1.30434783e-01
 3.61010830e-03 3.12500000e-01 2.07373272e-02 6.48379052e-02
 1.11607143e-01 7.80031201e-03 8.63930886e-02 1.70309395e-03
 5.66146736e-02 2.23684211e-01 1.45985401e-02 6.96864111e-03
 3.49180768e-03 2.22222222e-01 1.38613861e-01 9.61538462e-02
 1.03092784e-02 2.72727273e-01 2.01816347e-03 2.85714286e-01
 1.92592593e-01 1.39534884e-01 1.68032787e-01 1.09027475e-02
 1.17647059e-01 1.85185185e-01 7.14285714e-02 3.07017544e-02
 2.77777778e-02 1.59090909e-02 1.82504720e-02 8.00000000e-02
 1.53846154e-01 9.12698413e-02 9.56146657e-02 1.51020408e-01
 2.00000000e-01 1.96428571e-01 9.00900901e-03 3.76569038e-02
 2.15348473e-03 7.29927007e-03 2.58064516e-01 1.33333333e-01
 1.57004831e-01 4.49438202e-03 1.30750605e-01 1.31578947e-01
 3.22580645e-02 1.09090909e-01 1.11111111e-01 5.25164114e-02
 7.32984293e-02 1.33858268e-01 9.07563025e-02 3.57142857e-02
 5.00000000e-02 9.02061856e-02 3.18181818e-01 8.57142857e-02
 8.33333333e-02 5.07614213e-03 1.57556270e-01 2.22222222e-02
 7.76397516e-04 8.41793570e-02 2.67379679e-03 1.74603175e-01
 2.38095238e-02 1.81818182e-01 6.66666667e-02 9.09090909e-02
 1.97693575e-02 7.11743772e-03 4.97512438e-03 1.94003527e-01
 1.71638142e-01 2.14862682e-01 3.12500000e-02 9.47176685e-02
 1.42857143e-01 4.69483568e-03 2.41730280e-02 2.51968504e-01
 1.05263158e-01 1.15052733e-01 3.47133758e-01 4.00000000e-02
 3.00902708e-03 8.42839037e-02 1.25000000e-01 2.03252033e-01
 9.61313013e-02 6.57894737e-02 8.28729282e-02 2.33281493e-03
 2.80316880e-02 7.89473684e-02 1.27403846e-01 2.96610169e-01
 1.75675676e-01 2.50000000e-01 2.17391304e-01 2.18220339e-01
 6.52173913e-02 2.99940012e-04 1.40271493e-01 2.06896552e-02
 2.37288136e-01 5.80832527e-03 2.34064786e-01 2.16931217e-01
 1.66666667e-01]